### ISSUE TITLE
autoencoder example

### ISSUE THREAD

**Issue by puchacz-flyer** [kayuksel/forex-rl-challenge#3]
Thanks for sharing, very interesting results. However, I don't quite get what the VAE plots mean. The return (c) is plotted against the first element of the latent vector. I don't see a strong correlation between the two, which indicats the movement is captured?

https://github.com/kayuksel/forex-rl-challenge/blob/2ceb64e5bc71cb3e0a35278159337d1c541892b6/autoencoder.py#L94-L101

**Comment by zhenpingfeng** [comment]
Maybe this rl strategy is about outlier decision making not about regression prediction, so in this strategy, the correlation is not important as traditional predict strategy.

**Comment by akaniklaus** [comment]
@puchacz-flyer I apologize for the late response. Simply, the features which are provided are reduced and projected into a lower-dimensional space with a VAE, and then plotted against the return in the next period. What has been interesting is that the features especially correlates with large returns across any directions and generally ignores the small changes.

**Comment by kayuksel** [comment]
@puchacz-flyer I apologize for the late response. Basically, the features which are provided are reduced and projected into a lower-dimensional space with the help of VAE, and then plotted against the return in the next period. What has been an interesting finding is that the features especially correlates with large returns across any directions and generally ignores the small price changes.
